config/routes.rb
TictactoeWebsite::Application.routes.draw do

root :to => 'Tictactoe#game'
post 'tictactoe/player_moves', to: "tictactoe#player_moves", as: 'tictactoe_playermoves'
post 'tictactoe/new_game', to: "tictactoe#new_game", as: 'tictactoe_newgame'
   #get  '/tictactoe/playermoves', to: "Tictactoe#playermoves" ,as: 'tictactoe_playermoves'
  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tictactoe_controller.rb
require 'Tictactoe'
class TictactoeController < ApplicationController
  @winner = false
  @board_full = false
  before_filter :set_game
  def set_game 
    session[:game] = Tictactoe.new if session[:game].nil?
    session[:winner] = false if session[:winner].nil?
    @game = session[:game]
    session[:human_symbol] = "X" if session[:human_symbol].nil?
    session[:current_player] = "HU" if session[:current_player].nil?
    @winner = session[:winner]
  end

  def game
    @winner = session[:winner]
    session[:game] = Tictactoe.new
  end

  def new_game
    session[:game] = Tictactoe.new
    session[:winner] = false
    @winner = session[:winner]
    @game = session[:game]
    render :game
  end

  def player_moves
    p "PLAYER MOVES"
    if session[:current_player] == "HU" then
      if ( @game.playerMoves( Integer(params[:row]) ,Integer(params[:column]),"X") ) then
        session[:current_player] = "IA"
        winner(Integer(params[:row]),Integer(params[:column]),"X")
      end
    elsif ( @game.playerMoves( Integer(params[:row]) , Integer(params[:column]),"O")) then
      #game.IAMoves("O")
      session[:current_player] = "HU"
      winner(Integer(params[:row]),Integer(params[:column]),"O")
    end
    session[:game] = @game
    p "<<<<CURRENT BOARD>>>>"
    @game.printboard()
    @board_full = @game.isBoardFull()
    render :game
  end

  def winner(row, column,symbol)
    p "Checking winner...."
    if( @game.isAWinner(row, column,symbol))
      p "Player "<< symbol << " wins in positions: " << row << ", " << column
     @winner = true
      session[:winner] = true
    end
  end

  private

  def board_game
    @game ||= Tictactoe.new
    p "#" * 30
    @game.printboard
    p "#" * 30
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tictactoe_helper.rb
module TictactoeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TictactoeWebsite</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tictactoe/game.html.erb
<div align="center">
  <h1>Tictactoe</h1>
  </div>
  <div>

  <div align="center">
    <p>Calificaciones</p>

    <div> 
      <% if @winner %>
        <p> Player has won </p>
      <% elsif @board_full %>
          <p> Nobody wins </p>
      <% end %>
    
    </div>

    <table align="center">
      <tr>
        <td>
          <p><i> Player 1:</i></p>
        </td>
        <td width="30">
        </td>
        <td>
          <p><i>Player 2:</i></p>
        </td>
        <td width="30">
        </td>
      </tr>
    </table>
  </div>
  <div align="center" >
    <table>
      <% (0 ... 3).each do |row| %>
      <tr>
        <% (0 ... 3).each do |column| %>
        <td>
          <%= button_to @game.board[row][column].nil? ? "__": @game.board[row][column], 
            { :action => "player_moves", :row => row, :column => column }, 
            :disabled => @winner, :method => "post"%>
        </td>
      <% end %>
      </tr>
    <% end  %>
    </table>
  </div>
</div>
<div align="center" height = "150" valign = "center" >
    <%= button_to "Restart game", tictactoe_newgame_path, :method => "post"%>
  </div>

app/views/tictactoe/game_bckp.html.erb
<div align="center">
  <h1>Tictactoe</h1>
  </div>
  <div>

  <div align="center">
    <p>Calificaciones</p>

    <div> 
      <% if @winner %>
        <p> Player has won </p>
    <% end %>
    <% if @board_full %>
        <p> Nobody wins </p>
    <% end %>
    
    </div>

    <table align="center">
      <tr>
        <td>
          <p><i> Player 1:</i></p>
        </td>
        <td width="30">
        </td>
        <td>
          <p><i>Player 2:</i></p>
        </td>
        <td width="30">
        </td>
      </tr>
    </table>
  </div>
  <div align="center" >
    <table>
      <tr>
        <td>
          <%= button_to @game.board[0][0].nil? ? "__": @game.board[0][0], tictactoe_playermoves_path(row: "0", column:"0"), :disabled => @winner, :method => "post" %>
        </td>
        <td>
          <%= button_to @game.board[0][1].nil? ? "__": @game.board[0][1], tictactoe_playermoves_path(row: "0", column:"1"),  :disabled => @winner,:method => "post"%>
        </td>
        <td>
          <%= button_to @game.board[0][2].nil? ? "__": @game.board[0][2], tictactoe_playermoves_path(row: "0", column:"2"),  :disabled => @winner, :method => "post"%>
        </td>
      </tr>
      <tr>
        <td>
          <%= button_to @game.board[1][0].nil? ? "__": @game.board[1][0], tictactoe_playermoves_path(row: "1", column:"0"),  :disabled => @winner,:method => "post"%>
        </td>
        <td>
          <%= button_to @game.board[1][1].nil? ? "__": @game.board[1][1], tictactoe_playermoves_path(row: "1", column:"1"),  :disabled => @winner,:method => "post"%>
        </td>
        <td>
          <%= button_to @game.board[1][2].nil? ? "__": @game.board[1][2], tictactoe_playermoves_path(row: "1", column:"2"),  :disabled => @winner,:method => "post"%>
        </td>
      <tr>
        <td>
          <%= button_to @game.board[2][0].nil? ? "__": @game.board[2][0], tictactoe_playermoves_path(row: "2", column:"0"), :disabled => @winner, :method => "post"%>
        </td>
        <td>
          <%= button_to @game.board[2][1].nil? ? "__": @game.board[2][1], tictactoe_playermoves_path(row: "2", column:"1"),  :disabled => @winner,:method => "post"%>
        </td>
        <td>
          <%= button_to @game.board[2][2].nil? ? "__": @game.board[2][2], tictactoe_playermoves_path(row: "2", column:"2"), :disabled => @winner, :method => "post"%>
        </td>
      </tr>
    </table>
  </div>
</div>
<div align="center" height = "150" valign = "center" >
    <%= button_to "Restart game", tictactoe_newgame_path, :method => "post"%>
  </div>